name: Do The Docker Dew - JDK17-maven-git
on:
  push:
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: arc-runners
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Login to internal private docker repo
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.IMAGE_REGISTRY_HOST }}
        username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
        password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfiles/Dockerfile.jdk17-maven-git
        push: true
        tags: |
          ${{ vars.IMAGE_REGISTRY_HOST }}/${{ github.repository_owner }}/actions-runner-jdk17-maven-git:latest
          ${{ vars.IMAGE_REGISTRY_HOST }}/${{ github.repository_owner }}/actions-runner-jdk17-maven-git:${{ github.sha }}  
